# Generated by Django 4.2.4 on 2023-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_area_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
